# Homework1 

In [25]:
import numpy as np

### Тема “Вычисления с помощью Numpy”

Задание 1

In [3]:
a = np.array([[1, 2, 3, 3, 1], [6, 8, 11, 10, 7]])
mean_a = a.mean(axis=1)
mean_a

array([2. , 8.4])

Задание 2

In [12]:
a_centered = a.T - mean_a
a_centered = a_centered.transpose()
a_centered

array([[-1. ,  0. ,  1. ,  1. , -1. ],
       [-2.4, -0.4,  2.6,  1.6, -1.4]])

Задание 3

In [18]:
a_centered_sp = a_centered[0].dot(a_centered[1])
a_centered_sp

8.0

In [20]:
a_centered_sp/=a_centered.shape[1]
a_centered_sp

0.32

Задание 4

In [24]:
a_centered_cov = np.cov(a.T)
a_centered_cov

array([[12.5, 15. , 20. , 17.5, 15. ],
       [15. , 18. , 24. , 21. , 18. ],
       [20. , 24. , 32. , 28. , 24. ],
       [17.5, 21. , 28. , 24.5, 21. ],
       [15. , 18. , 24. , 21. , 18. ]])

### Тема “Работа с данными в Pandas”


In [26]:
import pandas as pd

Задание 1

In [29]:
authors = pd.DataFrame({'author_id': [1,2,3], 'author_name': ['Тургенев', 'Чехов', 'Островский']
})
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [32]:
book = pd.DataFrame({'author_id': [1, 1, 1, 2, 2, 3, 3], 'book_title': ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
                     'price': [450, 300, 350, 500, 450, 370, 290]})
book

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

Задание 2

In [33]:
authors_price = pd.merge(authors, book, on='author_id', how='inner')
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

Задание 3

In [37]:
top5 = authors_price.sort_values(by='price', ascending=False)[:5]
top5

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

Задание 4

In [46]:
authors_stat = authors_price.groupby('author_name').agg({"price":["min","max","mean"]})
authors_stat.columns=["min_price", "max_price","mean_price"]
authors_stat

min_price  max_price  mean_price
author_name                                  
Островский         290        370  330.000000
Тургенев           300        450  366.666667
Чехов              450        500  475.000000